FIx

diff --git a/.github/workflows/scrap_swingplanit.yml b/.github/workflows/scrap_swingplanit.yml
--- a/.github/workflows/scrap_swingplanit.yml
+++ b/.github/workflows/scrap_swingplanit.yml
@@ -17,7 +17,9 @@ jobs:
   
       - uses: r-lib/actions/setup-r@v2
       - name: Run script
-        run: Rscript scrap_swing_planit.R
+        run: |
+          set -x
+          Rscript scrap_swingplanit.R || { echo 'R script failed'; exit 1; }
         
       - name: Commit files
         run: |
